(defpackage :clap
  (:import-from :clap-builtin
                . #0=(#:range
                      #:all
                      #:any
                      #:bin
                      #:bit-length
                      #:oct
                      #:hex
                      #:bool
                      #:callable
                      #:chr
                      #:divmod
                      #:filter
                      #:fromhex
                      #:hash
                      #:int
                      #:isinstance
                      #:issubclass
                      #:len
                      #:enumerate
                      #:pow
                      #:raw-input
                      #:reversed
                      #:sorted
                      #:str
                      #:sum
                      #:zip
                      #:+whitespace-characters+
                      #:whitespacep
                      #:capitalize
                      #:center
                      #:count
                      #:endswith
                      #:expandtabs
                      #:find
                      #:index
                      #:isalnum
                      #:isalpha
                      #:isdigit
                      #:islower
                      #:isspace
                      #:istitle
                      #:isupper
                      #:join
                      #:ljust
                      #:lower
                      #:lstrip
                      #:partition
                      #:replace
                      #:rfind
                      #:rindex
                      #:rjust
                      #:rsplit
                      #:rstrip
                      #:split
                      #:splitlines
                      #:startswith
                      #:strip
                      #:swapcase
                      #:title
                      #:translate
                      #:upper
                      #:zfill
                      #:set
                      #:issubset
                      #:isupperset
                      #:union #:intersection
                      #:difference
                      #:symmetric-difference
                      #:isdisjoint
                      #:copy
                      #:dict
                      #:has-key
                      #:keys
                      #:values
                      #:fromkeys
                      #:lookup
                      #:setdefault
                      #:pop
                      #:get
                      #:items
                      #:popitem
                      #:update
                      #:del
                      #:flush
                      #:fileno
                      #:read
                      #:readline
                      #:readlines
                      #:seek
                      #:tell
                      #:write
                      #:writelines
                      #:define-class-method #:define-class-method-wrapper
                      #:not-implemented-yet
                      #:class-method-not-supported
                      #:value-error #:key-error))
  (:export . #0#)
  )
